#!/usr/bin/env bash
# One scheduled pressure-test run: pull, test, publish the report, notify.
#
# The report goes to an orphan `pressure-test-reports` branch, not to master.
# That keeps a dated history of pipeline health without putting churn in the
# branch you actually develop on, and without a bot ever pushing to master.
#
# Nothing in the report contains recording data: probes run on seeded
# synthetic spikes, and the only real paths recorded are repository-relative.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${REPO_ROOT}"

PY="${REPO_ROOT}/.hippo/bin/python"
[[ -x "${PY}" ]] || PY="$(command -v python3)"

STAMP="$(date -u +%Y-%m-%dT%H%M%SZ)"
HOST="$(hostname -s)"
REPORT_BRANCH="pressure-test-reports"
OUT_DIR="${REPO_ROOT}/reports/pressure_test"
PUBLISH="${PUBLISH:-1}"          # PUBLISH=0 to run without pushing

echo "=== hippo pressure test ${STAMP} on ${HOST} ==="

# 1. Sync. Never clobber local work: rebase, and bail out if it conflicts.
if git remote get-url origin >/dev/null 2>&1; then
  git fetch origin --quiet || echo "warn: fetch failed, testing local tree"
  BRANCH="$(git rev-parse --abbrev-ref HEAD)"
  if git rev-parse --verify --quiet "origin/${BRANCH}" >/dev/null; then
    if ! git -c rebase.autoStash=true pull --rebase --quiet origin "${BRANCH}"; then
      git rebase --abort 2>/dev/null || true
      echo "warn: rebase onto origin/${BRANCH} failed; testing the local tree as-is"
    fi
  fi
fi
HEAD_SHA="$(git rev-parse --short HEAD)"
echo "HEAD ${HEAD_SHA}"

# 2. The existing test suite first — a pressure test on a broken tree is noise.
echo "--- pytest ---"
"${PY}" -m pytest tests/ -q --no-header -p no:cacheprovider \
  > "${OUT_DIR}/pytest.txt" 2>&1 || true
mkdir -p "${OUT_DIR}"
tail -5 "${OUT_DIR}/pytest.txt" || true

# 3. The agent.
echo "--- pressure test ---"
"${PY}" -m agents.pressure_test --out "${OUT_DIR}" --fail-on none
AGENT_RC=$?

# 4. Publish to the report branch.
if [[ "${PUBLISH}" -eq 1 ]] && git remote get-url origin >/dev/null 2>&1; then
  echo "--- publish ---"
  TMP="$(mktemp -d)"
  cp -a "${OUT_DIR}/." "${TMP}/" 2>/dev/null || true

  if git rev-parse --verify --quiet "origin/${REPORT_BRANCH}" >/dev/null; then
    WT="$(mktemp -d)"
    git worktree add --quiet "${WT}" "origin/${REPORT_BRANCH}" --detach
    ( cd "${WT}"
      git switch --quiet -c "${REPORT_BRANCH}" 2>/dev/null || git switch --quiet "${REPORT_BRANCH}"
      mkdir -p "runs/${HOST}"
      cp -a "${TMP}/." "runs/${HOST}/"
      cp "${TMP}/report.md" "runs/${HOST}/${STAMP}.md" 2>/dev/null || true
      git add -A
      git -c user.name="hippo-agent" -c user.email="hippo-agent@${HOST}" \
          commit --quiet -m "pressure test ${STAMP} on ${HOST} @ ${HEAD_SHA}" || true
      git push --quiet origin "${REPORT_BRANCH}" || echo "warn: push failed"
    )
    git worktree remove --force "${WT}" 2>/dev/null || true
  else
    WT="$(mktemp -d)"
    git worktree add --quiet --detach "${WT}"
    ( cd "${WT}"
      git checkout --quiet --orphan "${REPORT_BRANCH}"
      git rm -rq --cached . 2>/dev/null || true
      find . -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} + 2>/dev/null || true
      mkdir -p "runs/${HOST}"
      cp -a "${TMP}/." "runs/${HOST}/"
      cp "${TMP}/report.md" "runs/${HOST}/${STAMP}.md" 2>/dev/null || true
      printf '# Pressure test reports\n\nGenerated by `agents/pressure_test`. Do not merge into master.\n' > README.md
      git add -A
      git -c user.name="hippo-agent" -c user.email="hippo-agent@${HOST}" \
          commit --quiet -m "pressure test ${STAMP} on ${HOST} @ ${HEAD_SHA}" || true
      git push --quiet -u origin "${REPORT_BRANCH}" || echo "warn: push failed"
    )
    git worktree remove --force "${WT}" 2>/dev/null || true
  fi
  rm -rf "${TMP}"
fi

# 5. Summary line for the cron log / systemd journal.
"${PY}" - "${OUT_DIR}/report.json" <<'PYEOF'
import json, sys
try:
    d = json.load(open(sys.argv[1]))
except Exception:
    sys.exit(0)
s = d["summary"]
print(f"SUMMARY {s['CRITICAL']} critical, {s['HIGH']} high, {s['MEDIUM']} medium, "
      f"{s['LOW']} low  ({d['environment'].get('elapsed_s')}s)")
for p in d["probes"]:
    for f in p["findings"]:
        if f["severity"] >= 3:
            print(f"  [{f['severity_label']}] {f['title']}")
PYEOF

exit 0
